//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forums_orig
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int Check_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<int> Session_ID { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Session Session { get; set; }
    }
}
