//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forums_orig
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Feed_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Members Members { get; set; }
    }
}
