//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forums_orig
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITForum2BDEntities1 : DbContext
    {
        private static ITForum2BDEntities1 _instance;

        public ITForum2BDEntities1()
            : base("name=ITForum2BDEntities1")
        {
        }

        public static ITForum2BDEntities1 GetInst()
        {
            if (_instance == null)
                _instance = new ITForum2BDEntities1();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckIn> CheckIn { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
