//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Forums_orig
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Reg_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Members Members { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
